FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf install -y \
    mesa-libGL \
    libXext \
    libXrender \
    libSM \
    libgomp \
    && dnf clean all \
    && rm -rf /var/cache/dnf

ENV HOME=/tmp
ENV TMPDIR=/tmp
ENV PADDLE_HOME=/tmp/paddle
ENV LD_LIBRARY_PATH=/usr/lib64:/usr/local/lib:/var/lang/lib/python3.12/site-packages/paddle/base:$LD_LIBRARY_PATH

COPY requirements.lambda.txt .

RUN pip install --no-cache-dir -r requirements.lambda.txt

COPY app ./app
COPY worker ./worker

CMD ["worker.lambda_handler.handler"]